DROP TABLE IF EXISTS comments, bookings, items, requests, users;

CREATE TABLE users (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY,
  name       VARCHAR(255) NOT NULL,
  email      VARCHAR(255) NOT NULL,
  CONSTRAINT pk_user PRIMARY KEY (id),
  CONSTRAINT uq_user_email UNIQUE (email)
);

CREATE TABLE requests
(
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY,
    description     VARCHAR(255) NOT NULL,
    requestor_id    INTEGER NOT NULL,
    created         TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_requests PRIMARY KEY (id),
    CONSTRAINT fk_requests_requestor FOREIGN KEY (requestor_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE items
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY,
    name        VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL,
    available   BOOLEAN      NOT NULL,
    owner_id    INTEGER      NOT NULL,
    request_id  INTEGER,
    CONSTRAINT  pk_item PRIMARY KEY (id),
    CONSTRAINT  fk_item_owner FOREIGN KEY (owner_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT  fk_item_request FOREIGN KEY (request_id) REFERENCES requests (id) ON DELETE CASCADE
);

CREATE TABLE bookings
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY,
    item_id    INTEGER,
    booker_id  INTEGER,
    start_date TIMESTAMP WITHOUT TIME ZONE,
    end_date   TIMESTAMP WITHOUT TIME ZONE,
    status     VARCHAR(255),
    CONSTRAINT pk_booking PRIMARY KEY (id),
    CONSTRAINT fk_booking_item FOREIGN KEY (item_id) REFERENCES items (id) ON DELETE CASCADE,
    CONSTRAINT fk_booking_booker FOREIGN KEY (booker_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE comments
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY,
    text        VARCHAR(255),
    item_id     INTEGER,
    author_id   INTEGER,
    created     TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_comments PRIMARY KEY (id),
    CONSTRAINT fk_comment_item FOREIGN KEY (item_id) REFERENCES items (id) ON DELETE CASCADE,
    CONSTRAINT fk_comment_author FOREIGN KEY (author_id) REFERENCES users (id) ON DELETE CASCADE
);